import type { Metadata } from 'next';
import { Header } from '@/components/layouts/header';

import './globals.css';

export const metadata: Metadata = {
  title: '인사이더',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css"
        />
      </head>
      <body style={{ fontFamily: 'Pretendard, sans-serif' }}>
        <Header />
        {children}
      </body>
    </html>
  );
}
