import type { Metadata } from 'next';
import { Header } from '@/components/layouts/header';
import { Footer } from '@/components/layouts/footer';
import { SideBar } from '@/components/layouts/sidebar';

import './globals.css';

export const metadata: Metadata = {
  title: '인사이더',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css"
        />
      </head>
      <body
        style={{ fontFamily: 'Pretendard, sans-serif' }}
        className="h-screen"
      >
        <main className="h-screen">
          <Header />
          <SideBar />
          <div className="flex w-screen justify-center">{children}</div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
